name: PSIRT Vulnerability Check

on:
  schedule:
    - cron: "0 0 */21 * *"  # Runs every 3 weeks (21 days)
  workflow_dispatch:  # Allows manual execution

jobs:
  run_psirt_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout output_excel Branch
      uses: actions/checkout@v4
      with:
        ref: output_excel  # Checkout the correct branch

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install requests pandas openpyxl

    - name: Run PSIRT Script
      env:
        OPENVULN_CLIENT_ID: ${{ secrets.OPENVULN_CLIENT_ID }}
        OPENVULN_CLIENT_SECRET: ${{ secrets.OPENVULN_CLIENT_SECRET }}
      run: python psirt_checker.py

    - name: Generate Output File Name
      run: |
        DATE=$(date +'%Y-%m-%d')
        OUTPUT_FILE="Baseline_albr_extract_$DATE.xlsx"
        echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV
        mv Baseline_albr_extract.xlsx "$OUTPUT_FILE"

    - name: Commit and Push Changes to output_excel
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add "$OUTPUT_FILE"
        git commit -m "Updated PSIRT vulnerability data ($OUTPUT_FILE)" || echo "No changes to commit"
        git push https://nilavan533:${GH_PAT}@github.com/nilavan533/psirt_test_1.git output_excel
