name: PSIRT Vulnerability Check

on:
  schedule:
    - cron: "0 0 */21 * *"  # Runs every 3 weeks (21 days)
  workflow_dispatch:  # Allows manual execution

jobs:
  run_psirt_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: output_excel  # Ensures we are working on the correct branch
        fetch-depth: 0  # Fetch full history to avoid issues with pulling

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # Ensure compatibility

    - name: Install Dependencies
      run: pip install requests pandas openpyxl

    - name: Run PSIRT Script
      env:
        OPENVULN_CLIENT_ID: ${{ secrets.OPENVULN_CLIENT_ID }}
        OPENVULN_CLIENT_SECRET: ${{ secrets.OPENVULN_CLIENT_SECRET }}
      run: python psirt_checker.py

    - name: Rename Excel Output with Date
      run: |
        DATE=$(date +'%Y-%m-%d')
        mv Baseline_albr_extract.xlsx Baseline_albr_extract_$DATE.xlsx

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Stash Local Changes Before Pull
      run: |
        git stash
        git pull --rebase origin output_excel || git rebase --abort
        git stash pop || echo "No changes to apply"

    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add Baseline_albr_extract_*.xlsx
        git commit -m "Updated PSIRT vulnerability data - $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push https://nilavan533:${GH_PAT}@github.com/nilavan533/psirt_test_1.git output_excel || echo "No changes to push"
