name: PSIRT Data Update

on:
  schedule:
    - cron: '0 0 1,22 * *'  # Runs at midnight UTC on the 1st and 22nd of each month
  workflow_dispatch:  # Allows manual execution

jobs:
  update-psirt-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Ensure your dependencies are installed

      - name: Run PSIRT Script
        run: python psirt_count_excel.py  # Execute the Python script

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add Baseline_albr_extract.xlsx
          git commit -m "Updated PSIRT vulnerability data"
          git push https://nilavan533:${GH_PAT}@github.com/nilavan533/psirt_test_1.git main
