name: Test Token Generation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  test_token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Test Token Generation
        env:
          OPENVULN_CLIENT_ID: ${{ secrets.OPENVULN_CLIENT_ID }}
          OPENVULN_CLIENT_SECRET: ${{ secrets.OPENVULN_CLIENT_SECRET }}
        run: python token_test.py
