name: PSIRT Vulnerability Check

on:
  schedule:
    - cron: "0 0 */21 * *"  # Runs every 3 weeks (21 days)
  workflow_dispatch:  # Allows manual execution

jobs:
  run_psirt_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to avoid push issues

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install requests pandas openpyxl

    - name: Run PSIRT Script
      env:
        OPENVULN_CLIENT_ID: ${{ secrets.OPENVULN_CLIENT_ID }}
        OPENVULN_CLIENT_SECRET: ${{ secrets.OPENVULN_CLIENT_SECRET }}
      run: python psirt_checker.py  # Ensure this script generates the Excel output

    - name: Rename Excel File with Date
      run: |
        DATE=$(date +'%Y-%m-%d')
        mv Baseline_albr_extract.xlsx Baseline_albr_extract_$DATE.xlsx

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Switch to Existing Output Branch
      run: |
        git checkout output_excel
        git pull --rebase origin output_excel  # Ensure latest changes

    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add Baseline_albr_extract_*.xlsx
        git commit -m "Updated PSIRT vulnerability data - $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push origin output_excel
